### ISSUE TITLE
add Slingshot to the list of network interconnects

### ISSUE THREAD

**Issue by adilger** [IO500/submission-system#8]
Please add the Slingshot interconnect (HPE/Cray) to the list of available network types.

**Comment by jeanbez** [comment]
@adilger we seem to have Slingshot there, should that be changed to include (HPE/Cray) alongside it?

**Comment by adilger** [comment]
I just checked now and don't see Slingshot as an option in the Interconnect description.

**Comment by adilger** [comment]
![Screen Shot 2024-04-13 at 17 39 42](https://github.com/IO500/submission-system/assets/167584/97074b55-6818-4f44-befd-8aa20a045093)

**Comment by jeanbez** [comment]
Thanks for double checking this, indeed we do not have in the "Interconnect" just on the "Network" component.
